const questionsDL = [
  {
    id: 1,
    q: "What is the fundamental computational unit in an artificial neural network?",
    qChinese: "人工神经网络中的基本计算单元是什么？",
    options: ["A) Synapse", "B) Perceptron", "C) Kernel", "D) Epoch"],
    optionsChinese: ["A) 突触", "B) 感知器", "C) 核", "D) 轮次"],
    answer: 1,
    explanation: "The perceptron is the fundamental computational unit in neural networks. It takes weighted inputs, sums them, applies an activation function, and produces an output. Invented by Frank Rosenblatt in 1958, it forms the building block for all modern deep learning architectures and multi-layer networks.",
    explanationChinese: "感知器是神经网络中的基本计算单元。它接收加权输入，求和后应用激活函数并产生输出。由Frank Rosenblatt于1958年发明，它构成了所有现代深度学习架构和多层网络的基础构件。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 2,
    q: "In a feedforward neural network, how does information flow?",
    qChinese: "在前馈神经网络中，信息如何流动？",
    options: ["A) In cycles between layers", "B) Only from input to output layer", "C) Backward from output to input", "D) Randomly between any layers"],
    optionsChinese: ["A) 在层之间循环", "B) 仅从输入层到输出层", "C) 从输出层反向到输入层", "D) 在任意层之间随机流动"],
    answer: 1,
    explanation: "In a feedforward neural network, information flows in one direction only: from the input layer through any hidden layers to the output layer. There are no cycles or loops. This unidirectional flow distinguishes feedforward networks from recurrent networks where connections can form cycles.",
    explanationChinese: "在前馈神经网络中，信息仅沿一个方向流动：从输入层经过隐藏层到输出层。没有循环或回路。这种单向流动将前馈网络与可以形成循环连接的循环网络区分开来。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 3,
    q: "What does the bias term in a neuron allow the model to do?",
    qChinese: "神经元中的偏置项允许模型做什么？",
    options: ["A) Increase training speed", "B) Shift the activation function", "C) Reduce overfitting", "D) Normalize inputs"],
    optionsChinese: ["A) 提高训练速度", "B) 移动激活函数", "C) 减少过拟合", "D) 归一化输入"],
    answer: 1,
    explanation: "The bias term allows the activation function to be shifted left or right, enabling the neuron to fit data that does not pass through the origin. Without bias, the model would be constrained to only learn patterns centered at zero, significantly limiting representational capacity.",
    explanationChinese: "偏置项允许激活函数左右移动，使神经元能够拟合不经过原点的数据。没有偏置，模型将被限制为只能学习以零为中心的模式，这将显著限制其表示能力。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 4,
    q: "What is the purpose of the hidden layers in a deep neural network?",
    qChinese: "深度神经网络中隐藏层的目的是什么？",
    options: ["A) To store training data", "B) To learn hierarchical feature representations", "C) To reduce the number of parameters", "D) To perform data augmentation"],
    optionsChinese: ["A) 存储训练数据", "B) 学习层次化的特征表示", "C) 减少参数数量", "D) 进行数据增强"],
    answer: 1,
    explanation: "Hidden layers learn hierarchical feature representations from the input data. Earlier layers capture low-level features like edges, while deeper layers combine these into higher-level abstractions like shapes and objects. This hierarchical learning is what gives deep networks their powerful representational ability.",
    explanationChinese: "隐藏层从输入数据中学习层次化的特征表示。较浅的层捕获边缘等低级特征，而更深的层将这些组合成形状和对象等高级抽象。这种层次化学习赋予了深度网络强大的表示能力。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 5,
    q: "How many trainable parameters does a fully connected layer have with 100 input neurons and 50 output neurons (including bias)?",
    qChinese: "一个有100个输入神经元和50个输出神经元的全连接层有多少可训练参数（包括偏置）？",
    options: ["A) 5000", "B) 5050", "C) 150", "D) 5100"],
    optionsChinese: ["A) 5000", "B) 5050", "C) 150", "D) 5100"],
    answer: 1,
    explanation: "A fully connected layer has weights plus biases as trainable parameters. With 100 inputs and 50 outputs, there are 100 x 50 = 5000 weight parameters plus 50 bias parameters (one per output neuron), totaling 5050 trainable parameters. Understanding parameter counts is crucial for model design.",
    explanationChinese: "全连接层的可训练参数包括权重和偏置。100个输入和50个输出产生100×50=5000个权重参数加上50个偏置参数（每个输出神经元一个），共计5050个可训练参数。理解参数数量对模型设计至关重要。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 6,
    q: "What does the Universal Approximation Theorem state?",
    qChinese: "通用近似定理说明了什么？",
    options: ["A) Deep networks always outperform shallow ones", "B) A single hidden layer network can approximate any continuous function", "C) Neural networks can solve any NP-hard problem", "D) More layers always lead to better accuracy"],
    optionsChinese: ["A) 深度网络总是优于浅层网络", "B) 单隐藏层网络可以近似任何连续函数", "C) 神经网络可以解决任何NP难问题", "D) 更多层总是带来更好的准确性"],
    answer: 1,
    explanation: "The Universal Approximation Theorem states that a feedforward neural network with a single hidden layer containing a finite number of neurons can approximate any continuous function on compact subsets of R^n. However, it does not guarantee efficient learning or practical feasibility of finding such approximations.",
    explanationChinese: "通用近似定理指出，具有包含有限数量神经元的单个隐藏层的前馈神经网络可以近似R^n的紧子集上的任何连续函数。但它不保证学习的效率或找到这种近似的实际可行性。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 7,
    q: "During the forward pass, what operation is performed at each neuron?",
    qChinese: "在前向传播过程中，每个神经元执行什么操作？",
    options: ["A) Gradient computation", "B) Weighted sum of inputs followed by activation", "C) Random weight initialization", "D) Loss calculation"],
    optionsChinese: ["A) 梯度计算", "B) 输入的加权和后接激活函数", "C) 随机权重初始化", "D) 损失计算"],
    answer: 1,
    explanation: "During the forward pass, each neuron computes a weighted sum of its inputs (z = Wx + b), then applies a nonlinear activation function f(z) to produce its output. This computation propagates layer by layer from input to output, generating the network prediction used for loss computation.",
    explanationChinese: "在前向传播过程中，每个神经元计算其输入的加权和（z = Wx + b），然后应用非线性激活函数f(z)产生输出。此计算逐层从输入传播到输出，生成用于损失计算的网络预测。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 8,
    q: "What problem can occur when training very deep neural networks with sigmoid activations?",
    qChinese: "使用sigmoid激活函数训练非常深的神经网络时会出现什么问题？",
    options: ["A) Exploding gradients only", "B) Vanishing gradient problem", "C) Memory overflow", "D) Data leakage"],
    optionsChinese: ["A) 仅梯度爆炸", "B) 梯度消失问题", "C) 内存溢出", "D) 数据泄漏"],
    answer: 1,
    explanation: "The vanishing gradient problem occurs when using sigmoid activations in deep networks because sigmoid squashes values to (0,1) and its maximum derivative is 0.25. Through backpropagation, gradients are multiplied across layers, causing them to shrink exponentially, making early layers nearly impossible to train.",
    explanationChinese: "使用sigmoid激活函数的深度网络会出现梯度消失问题，因为sigmoid将值压缩到(0,1)，其最大导数为0.25。在反向传播中，梯度跨层相乘，导致它们指数级缩小，使得早期层几乎无法训练。",
    diagram: "",
    terms: ["neural_network", "activation_function", "backpropagation"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 9,
    q: "Which weight initialization technique is recommended for ReLU activation functions?",
    qChinese: "对于ReLU激活函数，推荐使用哪种权重初始化技术？",
    options: ["A) Xavier initialization", "B) Zero initialization", "C) He initialization", "D) Uniform initialization"],
    optionsChinese: ["A) Xavier初始化", "B) 零初始化", "C) He初始化", "D) 均匀初始化"],
    answer: 2,
    explanation: "He initialization (Kaiming initialization) is designed specifically for ReLU activations. It sets weights from a normal distribution with variance 2/n, where n is the number of inputs. This accounts for ReLU zeroing out half of the values, maintaining proper signal variance through deep networks.",
    explanationChinese: "He初始化（Kaiming初始化）专门为ReLU激活函数设计。它从方差为2/n的正态分布中设置权重，其中n是输入数量。这考虑了ReLU将一半值置零的特性，在深度网络中维持适当的信号方差。",
    diagram: "",
    terms: ["neural_network", "activation_function"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 10,
    q: "What is the primary advantage of deep networks over shallow wide networks?",
    qChinese: "深度网络相比浅层宽网络的主要优势是什么？",
    options: ["A) Fewer hyperparameters to tune", "B) Faster training convergence", "C) Exponentially more efficient representation of complex functions", "D) Lower memory requirements"],
    optionsChinese: ["A) 更少的超参数需要调整", "B) 更快的训练收敛", "C) 对复杂函数的指数级更高效表示", "D) 更低的内存需求"],
    answer: 2,
    explanation: "Deep networks can represent complex functions exponentially more efficiently than shallow networks. Through hierarchical composition of simple features, deep networks build increasingly abstract representations. A function requiring exponentially many neurons in a shallow network may need only polynomially many in a deep architecture.",
    explanationChinese: "深度网络可以比浅层网络以指数级更高的效率表示复杂函数。通过简单特征的层次化组合，深度网络构建越来越抽象的表示。在浅层网络中需要指数级多神经元的函数，在深度架构中可能只需要多项式级别的神经元。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 11,
    q: "What does a softmax output layer produce?",
    qChinese: "softmax输出层产生什么？",
    options: ["A) Binary classification labels", "B) A probability distribution over classes", "C) Feature embeddings", "D) Gradient values"],
    optionsChinese: ["A) 二分类标签", "B) 类别上的概率分布", "C) 特征嵌入", "D) 梯度值"],
    answer: 1,
    explanation: "A softmax output layer converts raw logits into a probability distribution over all classes. Each output value is between 0 and 1, and all outputs sum to 1. This makes softmax ideal for multi-class classification tasks where we need to interpret outputs as class probabilities.",
    explanationChinese: "softmax输出层将原始logits转换为所有类别上的概率分布。每个输出值在0和1之间，所有输出之和为1。这使得softmax非常适合多分类任务，我们需要将输出解释为类别概率。",
    diagram: "",
    terms: ["neural_network", "activation_function"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 12,
    q: "What is the difference between a parameter and a hyperparameter?",
    qChinese: "参数和超参数之间有什么区别？",
    options: ["A) Parameters are set by users; hyperparameters are learned", "B) Parameters are learned during training; hyperparameters are set before training", "C) They are the same thing", "D) Hyperparameters only exist in CNNs"],
    optionsChinese: ["A) 参数由用户设置；超参数通过学习获得", "B) 参数在训练中学习；超参数在训练前设置", "C) 它们是同一回事", "D) 超参数仅存在于CNN中"],
    answer: 1,
    explanation: "Parameters like weights and biases are learned automatically during training through optimization. Hyperparameters like learning rate, batch size, and number of layers are set before training and control the learning process. Choosing good hyperparameters is crucial for achieving optimal model performance.",
    explanationChinese: "权重和偏置等参数在训练过程中通过优化自动学习。学习率、批量大小和层数等超参数在训练前设置，控制学习过程。选择好的超参数对于实现最优模型性能至关重要。",
    diagram: "",
    terms: ["neural_network", "optimizer"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 13,
    q: "What is an epoch in the context of neural network training?",
    qChinese: "在神经网络训练的语境中，什么是一个epoch？",
    options: ["A) One update of the weights", "B) One complete pass through the entire training dataset", "C) One batch of data processed", "D) One forward pass only"],
    optionsChinese: ["A) 一次权重更新", "B) 对整个训练数据集的一次完整遍历", "C) 处理一个批次的数据", "D) 仅一次前向传播"],
    answer: 1,
    explanation: "An epoch represents one complete pass through the entire training dataset. During one epoch, every training sample is seen exactly once. Training typically requires multiple epochs for convergence. Too few epochs cause underfitting, while too many may lead to overfitting if not properly regularized.",
    explanationChinese: "一个epoch代表对整个训练数据集的一次完整遍历。在一个epoch中，每个训练样本恰好被看到一次。训练通常需要多个epoch才能收敛。epoch太少会导致欠拟合，而太多如果没有适当正则化可能导致过拟合。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 14,
    q: "What is mini-batch gradient descent?",
    qChinese: "什么是小批量梯度下降？",
    options: ["A) Using the entire dataset for each update", "B) Using a single sample for each update", "C) Using a subset of the dataset for each update", "D) Skipping gradient computation"],
    optionsChinese: ["A) 每次更新使用整个数据集", "B) 每次更新使用单个样本", "C) 每次更新使用数据集的子集", "D) 跳过梯度计算"],
    answer: 2,
    explanation: "Mini-batch gradient descent uses a subset (mini-batch) of the training data for each parameter update. It balances between stochastic GD (one sample) and batch GD (full dataset). Mini-batches provide noisy but efficient gradient estimates, enabling faster training with good convergence properties and GPU parallelism.",
    explanationChinese: "小批量梯度下降使用训练数据的子集（小批量）进行每次参数更新。它在随机梯度下降（单个样本）和批量梯度下降（完整数据集）之间取得平衡。小批量提供有噪声但高效的梯度估计，实现更快的训练和良好的收敛特性以及GPU并行性。",
    diagram: "",
    terms: ["optimizer"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 15,
    q: "What is the purpose of a validation set in deep learning?",
    qChinese: "深度学习中验证集的目的是什么？",
    options: ["A) To train the model", "B) To tune hyperparameters and monitor overfitting", "C) To compute final test metrics", "D) To augment training data"],
    optionsChinese: ["A) 训练模型", "B) 调整超参数并监控过拟合", "C) 计算最终测试指标", "D) 增强训练数据"],
    answer: 1,
    explanation: "The validation set is used to tune hyperparameters and monitor overfitting during training. Unlike the test set, which evaluates final performance, the validation set provides feedback during model development. Early stopping, learning rate scheduling, and architecture choices are guided by validation performance.",
    explanationChinese: "验证集用于在训练过程中调整超参数和监控过拟合。与评估最终性能的测试集不同，验证集在模型开发过程中提供反馈。早停、学习率调度和架构选择都由验证性能指导。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 16,
    q: "What happens if all weights in a neural network are initialized to zero?",
    qChinese: "如果神经网络中的所有权重都初始化为零会发生什么？",
    options: ["A) The network trains faster", "B) Neurons in the same layer learn identical features (symmetry problem)", "C) The network automatically regularizes", "D) Gradients become very large"],
    optionsChinese: ["A) 网络训练更快", "B) 同一层的神经元学习相同的特征（对称性问题）", "C) 网络自动正则化", "D) 梯度变得非常大"],
    answer: 1,
    explanation: "Zero initialization causes the symmetry problem: all neurons in a layer compute identical outputs and receive identical gradients. They update identically and remain symmetric throughout training, effectively reducing the layer to a single neuron. Random initialization breaks this symmetry, allowing diverse feature learning.",
    explanationChinese: "零初始化会导致对称性问题：同一层中所有神经元计算相同的输出并接收相同的梯度。它们更新相同并在整个训练过程中保持对称，有效地将该层减少为单个神经元。随机初始化打破了这种对称性，允许多样化的特征学习。",
    diagram: "",
    terms: ["neural_network", "backpropagation"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 17,
    q: "What type of neural network architecture has connections that form directed cycles?",
    qChinese: "哪种神经网络架构具有形成有向循环的连接？",
    options: ["A) Feedforward network", "B) Convolutional network", "C) Recurrent network", "D) Autoencoder"],
    optionsChinese: ["A) 前馈网络", "B) 卷积网络", "C) 循环网络", "D) 自编码器"],
    answer: 2,
    explanation: "Recurrent neural networks (RNNs) have connections that form directed cycles, allowing information to persist across time steps. This feedback mechanism gives RNNs a form of memory, making them suitable for sequential data like time series, natural language, and speech where context from previous inputs matters.",
    explanationChinese: "循环神经网络（RNN）具有形成有向循环的连接，允许信息在时间步之间持续存在。这种反馈机制赋予RNN一种记忆形式，使其适用于时间序列、自然语言和语音等序列数据，其中来自先前输入的上下文很重要。",
    diagram: "",
    terms: ["rnn", "neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 18,
    q: "What is the typical pipeline order in a deep learning project?",
    qChinese: "深度学习项目的典型流程顺序是什么？",
    options: ["A) Train → Collect Data → Evaluate → Deploy", "B) Collect Data → Preprocess → Train → Evaluate", "C) Evaluate → Train → Collect Data → Deploy", "D) Deploy → Train → Evaluate → Collect Data"],
    optionsChinese: ["A) 训练 → 收集数据 → 评估 → 部署", "B) 收集数据 → 预处理 → 训练 → 评估", "C) 评估 → 训练 → 收集数据 → 部署", "D) 部署 → 训练 → 评估 → 收集数据"],
    answer: 1,
    explanation: "The standard deep learning pipeline follows: data collection, data preprocessing and augmentation, model design and training, evaluation on test data, then deployment. Each stage requires careful consideration. Data quality heavily influences model performance, making preprocessing a critical step in the pipeline.",
    explanationChinese: "标准深度学习流程遵循：数据收集、数据预处理和增强、模型设计和训练、在测试数据上评估，然后部署。每个阶段都需要仔细考虑。数据质量严重影响模型性能，使预处理成为流程中的关键步骤。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 19,
    q: "What is the role of a loss function in neural network training?",
    qChinese: "损失函数在神经网络训练中的作用是什么？",
    options: ["A) To initialize weights", "B) To measure the discrepancy between predictions and targets", "C) To select features", "D) To determine network architecture"],
    optionsChinese: ["A) 初始化权重", "B) 衡量预测和目标之间的差异", "C) 选择特征", "D) 确定网络架构"],
    answer: 1,
    explanation: "The loss function quantifies the discrepancy between the model's predictions and the true target values. It provides the optimization objective that training seeks to minimize. Different tasks use different loss functions: cross-entropy for classification, MSE for regression, enabling gradient-based parameter optimization.",
    explanationChinese: "损失函数量化模型预测与真实目标值之间的差异。它提供了训练寻求最小化的优化目标。不同的任务使用不同的损失函数：交叉熵用于分类，MSE用于回归，从而实现基于梯度的参数优化。",
    diagram: "",
    terms: ["loss_function", "neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 20,
    q: "What does 'depth' refer to in the context of deep learning?",
    qChinese: "在深度学习的语境中，'深度'指的是什么？",
    options: ["A) The amount of training data", "B) The number of layers in the network", "C) The number of parameters", "D) The training duration"],
    optionsChinese: ["A) 训练数据的数量", "B) 网络中的层数", "C) 参数的数量", "D) 训练持续时间"],
    answer: 1,
    explanation: "In deep learning, depth refers to the number of layers in the network, particularly the hidden layers between input and output. Networks with many layers are called deep networks. Greater depth enables learning more complex hierarchical representations, though it introduces challenges like vanishing gradients.",
    explanationChinese: "在深度学习中，深度指的是网络中的层数，特别是输入和输出之间的隐藏层。具有许多层的网络称为深度网络。更大的深度能够学习更复杂的层次化表示，但也引入了梯度消失等挑战。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 21,
    q: "Which of the following best describes a tensor in deep learning?",
    qChinese: "以下哪项最好地描述了深度学习中的张量？",
    options: ["A) A single number", "B) A multi-dimensional array of numbers", "C) A type of neural network", "D) A loss function"],
    optionsChinese: ["A) 单个数字", "B) 多维数字数组", "C) 一种神经网络", "D) 一种损失函数"],
    answer: 1,
    explanation: "A tensor is a multi-dimensional array that generalizes scalars (0D), vectors (1D), and matrices (2D) to higher dimensions. In deep learning, tensors are the fundamental data structure used to represent inputs, outputs, weights, and intermediate computations in frameworks like PyTorch and TensorFlow.",
    explanationChinese: "张量是一种多维数组，将标量（0维）、向量（1维）和矩阵（2维）推广到更高维度。在深度学习中，张量是用于表示输入、输出、权重和中间计算的基本数据结构，在PyTorch和TensorFlow等框架中使用。",
    diagram: "",
    terms: ["neural_network", "gpu_training"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 22,
    q: "What is the primary purpose of non-linear activation functions in neural networks?",
    qChinese: "神经网络中非线性激活函数的主要目的是什么？",
    options: ["A) To speed up computation", "B) To enable networks to learn non-linear decision boundaries", "C) To reduce memory usage", "D) To normalize outputs"],
    optionsChinese: ["A) 加速计算", "B) 使网络能够学习非线性决策边界", "C) 减少内存使用", "D) 归一化输出"],
    answer: 1,
    explanation: "Non-linear activation functions enable neural networks to learn complex, non-linear decision boundaries and mappings. Without non-linearity, stacking multiple linear layers would collapse into a single linear transformation, regardless of depth. Non-linear activations give networks the power to approximate any continuous function.",
    explanationChinese: "非线性激活函数使神经网络能够学习复杂的非线性决策边界和映射。没有非线性，堆叠多个线性层将折叠为单个线性变换，无论深度如何。非线性激活赋予网络近似任何连续函数的能力。",
    diagram: "",
    terms: ["activation_function", "neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 23,
    q: "What is batch size in the context of training neural networks?",
    qChinese: "在训练神经网络的语境中，什么是批量大小？",
    options: ["A) The total number of training samples", "B) The number of samples processed before updating weights", "C) The number of epochs", "D) The number of layers"],
    optionsChinese: ["A) 训练样本的总数", "B) 更新权重前处理的样本数", "C) 轮次数", "D) 层数"],
    answer: 1,
    explanation: "Batch size is the number of training samples processed before performing a weight update. Larger batches provide more stable gradient estimates but require more memory. Smaller batches introduce noise that can help escape local minima. Common batch sizes are powers of 2 like 32, 64, or 128.",
    explanationChinese: "批量大小是在执行权重更新之前处理的训练样本数。较大的批次提供更稳定的梯度估计但需要更多内存。较小的批次引入噪声，可以帮助逃离局部最小值。常见的批量大小是2的幂，如32、64或128。",
    diagram: "",
    terms: ["optimizer", "gpu_training"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 24,
    q: "What is the XOR problem and why is it significant in neural network history?",
    qChinese: "什么是XOR问题，为什么它在神经网络历史上很重要？",
    options: ["A) A data augmentation technique", "B) A problem showing single-layer perceptrons cannot solve non-linear tasks", "C) A regularization method", "D) A type of loss function"],
    optionsChinese: ["A) 一种数据增强技术", "B) 一个表明单层感知器无法解决非线性任务的问题", "C) 一种正则化方法", "D) 一种损失函数"],
    answer: 1,
    explanation: "The XOR problem demonstrated that a single-layer perceptron cannot classify non-linearly separable data. Minsky and Papert showed this limitation in 1969, causing an AI winter. The problem was later solved with multi-layer perceptrons and backpropagation, reviving interest in neural network research.",
    explanationChinese: "XOR问题证明了单层感知器无法分类非线性可分的数据。Minsky和Papert在1969年展示了这一限制，导致了AI寒冬。该问题后来通过多层感知器和反向传播得到解决，重新激发了对神经网络研究的兴趣。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  },
  {
    id: 25,
    q: "What is the output dimension of a neural network layer with 256 neurons?",
    qChinese: "具有256个神经元的神经网络层的输出维度是多少？",
    options: ["A) Depends on input dimension", "B) 256", "C) 128", "D) 512"],
    optionsChinese: ["A) 取决于输入维度", "B) 256", "C) 128", "D) 512"],
    answer: 1,
    explanation: "The output dimension of a fully connected layer equals the number of neurons in that layer, regardless of the input dimension. A layer with 256 neurons produces a 256-dimensional output vector. The input dimension determines the number of weights per neuron but not the output dimensionality.",
    explanationChinese: "全连接层的输出维度等于该层中的神经元数量，与输入维度无关。具有256个神经元的层产生256维输出向量。输入维度决定每个神经元的权重数量，但不决定输出维度。",
    diagram: "",
    terms: ["neural_network"],
    image: "",
    youtube: "",
    youtubeTitle: ""
  }
];

// Questions 26-50 are appended via separate parts
